name: "Hello Action World"
description: "Une action simple pour GitHub"
author: "Jensone"
inputs:
  name:
    description: "Nom de l'utilisateur"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - run ./entrypoint.sh
      shell: bash

branding:
  icon: "message"
  color: "blue"
